### ISSUE TITLE
The ignore symbol "@{" incorrectly rendered by SSG

### ISSUE THREAD

**Issue by sosias** [statamic/ssg#196]
### Bug description

The ignore symbols `@{` and `@}` are rendered correctly in the browser, but incorrectly by SSG.

This happens after the first occurrence of the `@{` and `@}` token onward. The first occurrence is correct, but the second and subsequent occurrences are not. (In a layout file and template file each independently)

### How to reproduce

In an antlers view **layout** file write this content `{{ "@{ @}" }}`

Create two pages that use this same layout.

This will render correctly in the browser as `{ }` but when generated via SSG it will produce two pages. One with the correct `{ }` content and the other one with the incorrect content:
```antlers
__antlers:leftBrace4578b435-2889-40a9-9d9a-5f3a4db4d7ab __antlers:rightBrace4578b435-2889-40a9-9d9a-5f3a4db4d7ab
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.44.0
PHP Version: 8.3.12
Composer Version: 2.8.2
Environment: local
Debug Mode: ENABLED
URL: statamic_empty_project.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.x-dev Solo

Statamic Addons
statamic/ssg: 3.1.1
```
