### ISSUE TITLE
Ignores the URL parameter of the site when using multisite

### ISSUE THREAD

**Issue by lotarbo** [statamic/ssg#199]
Hi, I want to try ssg to use for multisite. Now I've tested it - I get a strange result, it seems that URL is ignored.
I have two sites and want to put them on two separate domains.
```yml
en:
  name: en
  locale: en_US
  url: 'https://example.en'
es:
  name: es
  locale: es_ES
  url: 'https://example.es'

```
and it looks like this after running `php please ssg:generate` but I've got pages for every version
statamic:  5.53.0 
statamic/ssg: 3.1.1
<img width="431" alt="Image" src="https://github.com/user-attachments/assets/7b882b3b-6ef5-4596-87c7-511440febde3" />
