### ISSUE TITLE
External urls in navigation skipped

### ISSUE THREAD

**Issue by thomaskenne** [statamic/ssg#84]
Hi.

I have a `footer_navigation.yaml` file containing:
```
tree:
  -
    id: 35019694-9244-4bba-b453-667177f5d627
    entry: 4aae64ff-9519-4a9a-8eba-298d2acc516c
    title: Products
  -
    id: 4ffb78af-d33b-4fc6-8196-facec54c63df
    entry: ba77259e-ee06-4794-9711-3fdbdeedb23f
  -
    id: c315a3f3-7cc4-4ba0-b816-e365d76ffb1e
    entry: 84d90210-6db9-4937-8863-65b8c49150d0
  -
    id: 2f4bbb7d-9ae7-4ca2-930b-b6c25ef041e6
    entry: 32cbc527-cf57-4392-a867-cfeec52c9dd5
  -
    id: ccdebd88-bc83-4ab5-9c7d-5fb3d5de2a49
    entry: 19d4030e-0a64-43f3-b437-d8ecc7f3e4f1
  -
    id: 1a282940-465f-485c-ba53-cecd14930bfe
    entry: 6dd35d08-8aa5-4781-a7c6-70b23daa2e6f
  -
    id: eaa460cc-6928-4d55-bf26-975bac463bb5
    entry: 2711d102-e0df-4ae2-9d00-017b53ce91b7
  -
    id: 30135cc4-5348-4ba1-bf62-554c96a8c556
    entry: 2bf0f95b-2b9f-48fd-854a-ca2df941e768
  -
    id: 77d83009-7189-4d4d-ba92-d079c220fbd8
    title: 'Help desk'
    url: 'https://xyz.zendesk.com/'
```

The static generated files does not contain the last external link in the navigation. 
Any gotcha's I'm missing here?
